src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Le titre est obligatoire")]
    #[Assert\Length(
        min:5,
        max:255,
        minMessage:"La taille du titre doit être au minimum de 5 caractères",
        maxMessage:"La taille du titre doit être au maximum de 255 caractères")]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message:"La description est obligatoire")]
    #[Assert\Length(
        min:15,
        max:255,
        minMessage:"La taille de la description doit être au minimum de 15 caractères",
        maxMessage:"La taille de la description doit être au maximum de 255 caractères")]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Le type est obligatoire")]
    #[Assert\Length(
        min:3,
        max:255,
        minMessage:"La taille du type d'article doit être au minimum de 3 caractères",
        maxMessage:"La taille du type d'article doit être au maximum de 255 caractères")]
    private ?string $type = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank(message:"La catégorie est obligatoire")]
    private ?Category $category = null;

    #[ORM\Column(length: 255)]
    private ?string $link = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ArticleType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration(
                "Titre",
                "Rentrez un titre"
            ))
            ->add('description', TextareaType::class, $this->getConfiguration(
                "Description",
                "Rentrez une description",
                [
                    'attr' => [
                        'rows' => 5,
                        'class' => "p-3 mt-1 w-full"
                    ]
                ]
            ))
            ->add('type', TextType::class, $this->getConfiguration(
                "Type d'article",
                "Vidéo, article, doc ..."
            ))
            ->add('link', TextType::class, $this->getConfiguration(
                "Lien de l'article",
                "Rentrez un lien"
            ))
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'label' => 'Catégorie',
                'placeholder' => 'Choisir une catégorie'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Category;
use App\Form\ArticleType;
use App\Repository\UserRepository;
use App\Repository\ArticleRepository;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ArticleController extends AbstractController
{
    #[Route('/articles', name: 'article.index')]
    public function index(ArticleRepository $articleRepository): Response
    {
        $articles = $articleRepository->orderByDateDESC();
        return $this->render('article/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    #[Route('/article/nouveau', name: 'article.new')]
    #[Security("is_granted('ROLE_USER')")]
    public function create (Request $request, EntityManagerInterface $em, UserRepository $userRepository)
    {
        $article = new Article();
        $articleType = $this->createForm(ArticleType::class, $article);
        $articleType->handleRequest($request);
    
        if($articleType->isSubmitted() && $articleType->isValid()){
            $article->setCreatedAt(new \DateTime('now'))
            ->setAuthor($this->getUser());
            $em->persist($article);
            $em->flush();

            $this->addFlash(
                'success',
                "Article créé"
            );

            return $this->redirectToRoute('article.index');
        }

        return $this->render('article/new.html.twig', [
            'articleType' => $articleType->createView()
        ]);
    }

    #[Route('/article/modification/{id}', name: 'article.edit')]
    #[Security("is_granted('ROLE_USER')")]
    public function edit(Request $request, Article $article, EntityManagerInterface $em)
    {
        $articleType = $this->createForm(ArticleType::class, $article);
        $articleType->handleRequest($request);

        if($articleType->isSubmitted() && $articleType->isValid()){
            $article->setAuthor($this->getUser());
            $em->persist($article);
            $em->flush();

            $this->addFlash(
                'success',
                "Article modifié"
            );

            return $this->redirectToRoute('article.index');
        }
        return $this->render('article/edit.html.twig', [
            'articleType' => $articleType->createView()
        ]);
    }

    #[Route('/article/suppression/{id}', name: 'article.delete')]
    #[Security("is_granted('ROLE_USER')")]
    public function delete(Article $article, EntityManagerInterface $em)
    {
        $em->remove($article);
        $em->flush();
        $this->addFlash(
            'danger',
            "Article supprimé"
        );
        return $this->redirectToRoute('article.index');
    }

    #[Route('/articles/{id}', name: 'category.showArticleByCategory')]
    public function showArticlesByCategory(Category $category, ArticleRepository $articleRepository, CategoryRepository $categoryRepository): Response
    {
        $articles = $articleRepository->findBy(['category' => $category]);
        $categoryName = $categoryRepository->find($category)->getName();
        return $this->render('article/index.html.twig', [
            'articles' => $articles,
            'categoryName' => $categoryName
        ]);
    }
}

templates/article/edit.html.twig
{% extends "base.html.twig" %}
{% block title %}
    Nouveau Article
{% endblock %}
{% block body %}
{% include "partials/header.html.twig" %}
   <div class="flex flex-col justify-between items-between mr-auto ml-auto p-5 my-10 w-1/2">
     {{ form_start(articleType) }}
	{{ form_widget(articleType) }}
	<div class="flex justify-center">
		<button type="submit" class="bg-transparent text-green-500 border-2 border-green-500 hover:bg-green-500 hover:text-white py-2 px-4">Sauvegarder</button>
	</div>
	{{ form_end(articleType) }}
   </div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Articles{% endblock %}
{% block body %}
{% include "partials/header.html.twig" %}
   <div class="my-4 flex justify-around items-center w-full">
	{% if categoryName is defined %}
        <h1 class="text-4xl">{{ categoryName }}</h1>
    {% else %}
        <h1 class="text-4xl">Liste des articles</h1>
    {% endif %}
    
	{% if app.user %}
        <a href="{{path('article.new')}}">
		    <i class="text-2xl fa-solid fa-circle-plus hover:cursor-pointer hover:text-blue-700"></i>
	    </a>
    {% endif %}
    
</div>
   <div class="overflow-x-auto h-full mt-5">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="py-3 px-6 text-center">
                    Titre <i id="icon_title_sort" class="hover:text-blue-700 hover:cursor-pointer fas fa-solid fa-sort mx-2"></i>
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                    Categorie <i id="icon_category_icon" class="hover:text-blue-700 hover:cursor-pointer fas fa-solid fa-sort mx-2"></i>
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                    Type <i id="icon_type_sort" class="hover:text-blue-700 hover:cursor-pointer fas fa-solid fa-sort mx-2"></i>
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                    Lien <i id="title" class="hover:text-blue-700 hover:cursor-pointer fas fa-solid fa-sort mx-2"></i>
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                    Auteur <i id="icon_author_sort" class="hover:text-blue-700 hover:cursor-pointer fas fa-solid fa-sort mx-2"></i>
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                    Date création <i id="icon_author_sort" class="hover:text-blue-700 hover:cursor-pointer fas fa-solid fa-sort mx-2"></i>
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <td class="text-center py-4 px-6">
                        {{article.title}}
                    </td>
                    <td class="text-center py-4 px-6">
                        <a href="{{path('category.showArticleByCategory', {'id' : article.category.id}) }}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline text-center">{{article.category.name}}</a>
                    </td>
                    <td class="text-center py-4 px-6">
                        {{article.type}}
                    </td>
                    <td class="text-center py-4 px-6 hover:text-blue-700">
                        <a href="http://{{article.link}}" target="_blank">{{article.link}}</a>
                    </td>
                    <td class="text-center py-4 px-6">
                        {{article.author.username}}
                    </td>
                    <td class="text-center py-4 px-6">
                        {{article.createdAt | date('d-m-Y')}}
                    </td>
                    <td class="text-center py-4 px-6">
                    {% if app.user and (app.user.id == article.author.id or is_granted('ROLE_ADMIN')) %}
                        <a href="{{path('article.delete', {'id' : article.id}) }}" class="font-medium text-red-600 dark:text-blue-500 hover:underline"><i class="fa-solid fa-trash-can"></i></a>
                            <a href="{{path('article.edit', {'id' : article.id}) }}" class="font-medium text-green-600 dark:text-blue-500 hover:underline"><i class="fa-solid fa-pen-to-square"></i></a>
                    {% endif %}
                    
                </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/article/new.html.twig
{% extends "base.html.twig" %}
{% block title %}
    Nouveau Article
{% endblock %}
{% block body %}
{% include "partials/header.html.twig" %}
   <div class="flex flex-col justify-between items-between mr-auto ml-auto p-5 my-10 w-1/2">
     {{ form_start(articleType) }}
	{{ form_widget(articleType) }}
	<div class="flex justify-center">
		<button type="submit" class="bg-transparent text-green-500 border-2 border-green-500 hover:bg-green-500 hover:text-white py-2 px-4">Sauvegarder</button>
	</div>
	{{ form_end(articleType) }}
   </div>
{% endblock %}